# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

remote_theme: "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin: "dark"

# Site settings
locale: "en"
title : "Guille Gonzalez"
title_separator: "-"
subtitle: "Occasionally writing about Swift"
name: &name "Guille Gonzalez"
description: &description "Occasionally writing about Swift."
url: https://gonzalezreal.github.io
baseurl: ""
repository: "gonzalezreal/gonzalezreal.github.io"
github: [metadata]
words_per_minute: 200
paginate: 5
paginate_path: /page:num/
search: true
search_full_content: true

# SEO Related
google_site_verification : "matIXerNckmaoAKnzFBbnMlHjFFx97VSj_Uv3BG1pnY"

# Social
twitter:
  username: &twitter "gonzalezreal"
og_image: /assets/images/me.jpeg
social:
  links:
    - "https://twitter.com/gonzalezreal"
    - "https://github.com/gonzalezreal"
    - "https://www.linkedin.com/in/guillermogonzalezreal/"

# About
author:
  name: *name
  avatar: /assets/images/me.jpeg
  bio: "Occasional **mobile developer**. Jira ticket pusher. Converting coffee into code since the nineties. Comic book lover and movie buff."
  location: "Madrid, Spain"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gonzalezreal"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gonzalezreal"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guillermogonzalezreal/"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gonzalezreal"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gonzalezreal"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guillermogonzalezreal/"
      
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
